version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_dev
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=http://qdrant:6333
      - QDRANT_PORT=6333
    volumes:
      - .:/app
    networks:
      - fastapi_network
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
